### ISSUE TITLE
ERC20 icons all went to the fallback

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#107]
Perhaps I am getting the service worker issue again? These seem like the old icons?

![img_1725](https://user-images.githubusercontent.com/438160/38656798-c66433a8-3dea-11e8-92e8-55dc13f5cee0.JPG)

**Comment by mikedemarais** [comment]
@ricburton I do think this is happens when running the project locally.

I fixed [the issue with the flickering icons](https://cl.ly/3A02051N1347) here though ➡https://github.com/balance-io/balance-manager/pull/211

**Comment by mikedemarais** [comment]
**UPDATE** 😜

@ricburton Confirmed. This **does** only happen when the project is run locally. 

It's happening because the `token` image assets are linked as a `git submodule` and therefore image files are not being downloaded to your local machine by default. (https://github.com/balance-io/balance-manager/blob/latest/.gitmodules)

To solve the issue while running the project locally.. Run this command in the root directory of your `balance-manager` git repo:

```
git submodule update --init --recursive
```

I updated my PR to add this command to the project's `README.md` instructions. https://github.com/balance-io/balance-manager/pull/211/commits/e07de90a95828a5f89a66e4ab003b2a1d683cb7b
