### ISSUE TITLE
🏎 Trade engine

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#204]
We need to build a system that can tap into the liquidity of all of the decentralised exchanges to fulfill larger orders. It should ingest all of them:

https://0xproject.com/
https://airswap.io/
https://kyber.network/
https://uniswap.io/
https://dexy.exchange/

Then when people place an order it should find the right way to do it. This gets harder when the value goes up: 

$10
$100
$1000
$10,000
$100,000
$1,000,000

**Comment by kwikiel** [comment]
AFAIK https://airswap.io/ is already doing that - and it seems easiest to integrate.  One is creating request to buy/sell specific coins and the liquidity providers are specific offering terms

**Comment by ricburton** [comment]
It is not aggregating multiple exchanges which have different liquidity options.

Richard

Sent via Superhuman ( https://sprh.mn/?vip=richard@balance.io )

**Comment by kwikiel** [comment]
I've actually did some research on AirSwap and IMHO it's much more superior than other solutions:

There are two ways to facilitate a trade:
- orderbook + relayers
- broker

<img width="517" alt="screen shot 2018-07-01 at 05 16 24" src="https://user-images.githubusercontent.com/5274399/42130744-f57327ac-7ced-11e8-8832-75a655c51c6c.png">

So AirSwap works much better than 0x or ShapeShift for Balance because it's fitting exchange model:
- user is saying that he wants to exchange 100 tokens for $100
- taker is actually aggregating multiple exchanges (they can be decentralized or centralized/custodian)

"The Order API is off-chain and specifies asynchronous calls made between counterparties during trade negotiation. An implementor may choose to serve a request-provide cycle as a synchronous request-response. Because an order is signed by the Maker, the Taker is able to later submit it to the smart contract to be filled."

<img width="453" alt="screen shot 2018-07-01 at 05 20 25" src="https://user-images.githubusercontent.com/5274399/42130754-7e41bee0-7cee-11e8-8de5-27bc8cf8a582.png">

So Balance can either manually integrate multiple exchanges or just become AirSwap indexer (liquidity provider) - IMHO much more profitable

**Comment by ricburton** [comment]
I would love to hear what @haydenadams thinks about these options.

We are definitely keen on Airswap.

**Comment by jinchung** [comment]
Closing this for now as we will be revisiting our exchange aggregator situation after other priorities.
