### ISSUE TITLE
🗣 Add language selector to wallet connection page

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-manager#264]
The language selector should show up on the wallet connection page

<img width="259" alt="screen shot 2018-06-07 at 15 49 58" src="https://user-images.githubusercontent.com/438160/41122742-8035c94e-6a6a-11e8-9f56-1268ae358030.png">

**Comment by abstractpoint** [comment]
Added the selector, but also re-arranged the order of elements so that language is always last, that way it is in the same position when going from view to view. PR #273

![screen shot 2018-06-09 at 20 04 51](https://user-images.githubusercontent.com/3032975/41195156-5b087f56-6c20-11e8-831e-6db71dea90ff.png)
![screen shot 2018-06-09 at 20 03 52](https://user-images.githubusercontent.com/3032975/41195157-5b205f40-6c20-11e8-809d-bd368c9b6a59.png)

**Comment by ricburton** [comment]
@abstractpoint that's a really nice touch

Thank you!
